@startuml
left to right direction

actor Pengunjung
actor Admin

rectangle Website {
    Pengunjung -- (Intro)
    Pengunjung -- (Members)
    Pengunjung -- (About)
    Pengunjung -- (Contact)
    Pengunjung -- (Play/Mute Musik)

    Admin -- (Login)
    (Login) --> (Tambah Member) : <<include>>
    (Login) --> (Hapus Member) : <<include>>
    (Login) --> (Edit Member) : <<include>>
}

@enduml